#!/bin/bash

set -e
set -u

TIMER=''
JOB=''
KETTLE_HOME=''
KETTLE_JNDI_ROOT=''
DEBUGLEVEL=''
LOGNAME=''
KETTLE_PAT=''
KETTLE_LOG=''


function setEnvironment
{
    export KETTLE_HOME=$1
    export KETTLE_JNDI_ROOT=$KETTLE_HOME
}

function _console(){
    local message=${1:-''}
    [[ -n "$message" ]] && echo -e "$message"
}

function _die(){
    local message=${1:-''}
    local exit_code=${2:-0}
    _console "$message"
    exit $exit_code
}

function timer(){
 export TIMER='time';
}

function getPdi(){
    process_id='/bin/ps -fu $USER| grep "$1" | grep -v "grep" | awk '{print $1}''
    _console $process_id
    export $process_id;
}

function help(){
cat <<EOF
    Usage: hells_kitchen.sh <[options]>
    Options:
        -t = time (Optional)
        -j = job file (ktr or kjb)
        -l = bug level in pdi:
             Error: Only show errors
             Nothing: Don't show any output
             Minimal: Only use minimal logging
             Basic: This is the default basic logging level (Default)
             Detailed: Give detailed logging output
             Debug: For debugging purposes, very detailed output.
             Rowlevel: Logging at a row level, this can generate a lot of data.
             Stream: No log show the content
        -e = dynamic envairoment (please see the secction enviaroment) (Optional)
        -p = path of pdi (Optinal)
        -ln= path of log folder (Optinal)
EOF
_die
}

function stove(){

    local job=${1:-''}
    local debug_level=${2:-'Basic'}
    local log_name=${3:-''}
    local timer=${4:-''}
    local kettle_path=${5:-''}
    local kettle_log=${6:-''}

    local now=$(date -u +%Y%0m%0d%H%M%S)
    local log_pattor="${kettle_log}${log_name}_${now}.log"
    #echo $environment

    ##
    # ::if don't exit the job ::
    #
    if [ !-e $job ]; then
        _die "Error!!!! the ETL process don't exist please check the path" 4
    fi

    cd $kettle_path
    if [[ $job =~ \.kjb$ ]]; then
        cmd="$timer ./kitchen.sh -file=$job -level=$debug_level  >> $kettle_log"
    else
        cmd="$timer ./pan.sh -file=$job -level=$debug_level  >> $kettle_log"
    fi

    _console "Executing: $cmd"

    sleep 1
    eval $cmd 2>>$kettle_log
    case  $?  in
        0) _console "The job ran without a problem." >> $kettle_log ;;
        1) _console "Errors occurred during processing" >> $kettle_log ;;
        2) _console "An unexpected error occurred during loading / running of the job" >> $kettle_log ;;
        7) _console "The job couldn't be loaded from XML or the Repository" >> $kettle_log ;;
        8) _console "Error loading steps or plugins (error in loading one of the plugins mostly)" >> $kettle_log ;;
        9) _console "Command line usage printing" >> $kettle_log ;;
        *) _console "Unknown error code: $?" >> $kettle_log ;;
    esac 
}

##
# ::main::
#
while getopts ":t:j:l:e:p:ln:h" opts; do
      case ${opts} in
           t)  TIMER=${OPTARG};;
           j)  JOB=${OPTARG} ;;
           l)  LOGNAME=${OPTARG};;
           e)  setEnvironment ${OPTARG};;
           p)  KETTLE_PAT=${OPTARG};;
           ln) KETTLE_LOG=${OPTARG};;
           h)  help;;
          \?)  echo "1" ;;
           :)  echo "2" ;;
           *)  echo "3" ;;
      esac
 done

##
# ::launcher::
#
stove $JOB $DEBUGLEVEL $LOGNAME $TIMER $KETTLE_PAT $KETTLE_LOG